[package]
name = "bevyquad-profiler"
version = "0.2.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"
description = "Profiler UI for bevyquad"
license = "MIT/Apache-2.0"

[dependencies]
bevyquad = { path = "../", version = "0.4" }
